#!/usr/bin/env bash

# Transfer suitable events from new-events/ to queued/events/.
# Matches 'patchset-created' or a 'recheck' comment on the target project.

for event in $(ls -1tr ${CI_NEW_EVENTS?}); do
    f="${CI_NEW_EVENTS?}/$event"
    if grep -q -e "^ *\"project\": \"${CI_PROJECT}" $f &&
       grep -q -e "^ *\"comment\": \"recheck (no )* bug" \
               -e "^ *\"type\": \"patchset-created\"" $f; then
	echo "Accepted $event"
	mv $f ${CI_QUEUED_EVENTS?}
    else
	[ -d "${CI_SKIPPED_EVENTS?}" ] && mv $f ${CI_SKIPPED_EVENTS} || rm $f
    fi
done

