#!/usr/bin/env bash

ssh -p 29418 ${CI_SSH_OPTS} ${CI_SSH_USER?}@review.openstack.org gerrit stream-events |
  (while read line; do
      id=$(uuidgen)
      echo "$line" | python -mjson.tool > ${CI_NEW_EVENTS?}/$id
      echo "Wrote $id"
   done)

