#!/usr/bin/env bash

# Mandatory Parameters:
#   CI_COMMENT: Started with PASSED or FAILED.
#   CI_COMMIT:  Commit ID that is being voted on.
#
# Optional Parameters:
#   CI_NO_NEGATIVE: Vote 0 instead of -1. (During debug.)

vote="0"
if echo ${CI_COMMENT?} | grep -i '^passed'; then
    vote="+1"
elif echo ${CI_COMMENT?} | grep -i '^failed'; then
    vote="-1"
fi

ssh -p 29418 ${CI_SSH_OPTS} ${CI_SSH_USER?}@review.openstack.org \
    gerrit vote --code-review "${vote}" --message "${CI_COMMENT?}"
