Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-trusty-for-ci"
  config.vm.provision "shell", inline: "su vagrant -c /vagrant/inside-vagrant.sh | tee /vagrant/console.log"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "shellci" + (ENV["CI_SHARD"] or "")
    vb.customize ["modifyvm", :id, "--memory", "4096"]
  end
end
